name: Daily Stock Tracker Function
on:
  schedule:
    - cron: "30 08 * * *" # Cada día a las 9:30 hora española, UT 08:30
  workflow_dispatch: 

jobs:
  run_stock_tracker:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necesitas permisos para escribir si esta función también genera archivos que debas commitear
    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necesario para operaciones de Git

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies with uv
        run: uv pip install . --system
      - name: Run the weekly specific function
        run: |
          echo "Running weekly specific function..."
          uv run main_stock.py
