name: Lunes 12PM. Weekly Newsletter Function

on:
  schedule:
    - cron: "30 11 * * 1" # Cada lunes a las 11:30 UTC, 13:30 hora española
  workflow_dispatch: # Permite ejecutar el workflow manualmente

jobs:
  run_weekly_function:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Necesitas permisos para escribir si esta función también genera archivos que debas commitear
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      USER_POOL_ID: ${{ secrets.USER_POOL_ID }}
      SUMMARIES_FOLDER: web/data/summaries
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Necesario para operaciones de Git

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install dependencies with uv
        run: uv pip install . --system
      - name: Run the weekly specific function
        run: |
          echo "Running weekly specific function..."
          uv run python main.py pipeline-semanal --no-debug
